### ISSUE TITLE
Some code doesn't execute?

### ISSUE THREAD

**Issue by xpbliss** [jeevatkm/jwtauth#2]
In the sample, some code doesn't execute? as the following:

revel.OnAppStart(func() {
    jwt.Init(jwt.AuthHandlerFunc(func(username, password string) (string, bool) {
        revel.INFO.Printf("Username: %v, Password: %v", username, password)// does not execute?
fmt.Println(username, password)   // does not execute?
        userId := 100001
        authenticated := true          
        return fmt.Sprintf("%d", userId), authenticated
    }))
})

**Comment by jeevatkm** [comment]
That function invoked by `JwtAuth` controller while accessing `/token` route.

For example:
POST `/token`
Body:
```json
{
     "username": "user2@myjeeva.com",
     "password": "user2"
}
```

It will print like this in the stderr and returns token in the response
`INFO  2015/09/08 16:46:06 app.go:73: Username: user2@myjeeva.com, Password: user2`

Am I missing?

**Comment by xpbliss** [comment]
The sample may missing something.

**Comment by jeevatkm** [comment]
Took fresh checkout from github. And followed instructions for running a application. It's running!

Body content is not part of sample. Because sample application is exactly real-time scenario, no static values except user credentials.  So it needs to be posted to /token. 

You can use any rest client to do quick test with values mentioned in the previous comment.

Tomorrow I will document couple of steps in sample readme file. Thanks!

**Comment by jeevatkm** [comment]
[Readme](https://github.com/jeevatkm/jwtauth/blob/master/example/jwtauth-example/README.md) file updated with sample application documentation.
